### ISSUE TITLE
Hello from testcontainers-go! 👋 

### ISSUE THREAD

**Issue by mdelapenya** [stillya/testcontainers-keycloak#1]
Hi! First thanks for creating a keycloak module using testcontainers-go!! 🚀  I looked at the code and it's pretty similar to what we internally create, so thank you so much for following our guides for creating modules 🙇 

I'm here to share with you [our module catalog](https://github.com/testcontainers/community-module-registry), just in case you want to add your module to the list, basically here: https://testcontainers.com/modules/keycloak/

If you have any question, feel free to reach out here in the issue, or in our slack https://testcontainers.slack.com

Thanks in advance!

**Comment by stillya** [comment]
Hello @mdelapenya!
Thank you for checking out the module.
I'd be more than happy to add my module to the Testcontainers catalog. You can find the PR [here](https://github.com/testcontainers/community-module-registry/pull/10).

**Comment by mdelapenya** [comment]
I think we can close this issue, as it now appears under our modules catalog: https://testcontainers.com/modules/keycloak/

Thanks for your hard work with Testcontainers 💪 , and please let us know if you have any question 🙏
