### ISSUE TITLE
Upgrade to Testcontainers v0.31

### ISSUE THREAD

**Issue by tricktron** [stillya/testcontainers-keycloak#6]
Testcontainers v0.31 contains [breaking changes](https://github.com/testcontainers/testcontainers-go/releases/tag/v0.31.0) and therefore this module cannot be used with the newest version or with other testcontainer modules who already use v0.31.0.

**Comment by stillya** [comment]
Hello. You're absolutely right. I was busy for a couple of weeks, but I believe this can be resolved within a week.
_P.S. I also think it would be useful for the testcontainers-keycloak module to have an error propagation API._

**Comment by stillya** [comment]
Resolved by [PR](https://github.com/stillya/testcontainers-keycloak/pull/8).
